### ISSUE TITLE
Can unearth read from ~/.pip/pip.conf ?

### ISSUE THREAD

**Issue by SurenNihalani** [frostming/unearth#13]
**Is your feature request related to a problem? Please describe.**
I'd like unearth to implicitly pick up the internal index url from pip.conf

**Comment by Hnasar** [comment]
This would also help our company port to PDM 2.0.

**Comment by frostming** [comment]
`pip` has three layers of OS-dependent configuration files and supports overriding via env vars. Ref: https://pip.pypa.io/en/stable/topics/configuration/

It is over-complicated to read such configurations which are not part of `unearth` itself, unless we hard depend on `pip`. IMO it is not worth the effort. @Hnasar PDM 2.0 has its own configurations of PyPI URLs, why would you still rely on the pip conf if you are going to port to PDM?

**Comment by Hnasar** [comment]
@frostming at Beta we have ~50 python projects. Previously we had all devs configure a pip.conf so that `pip` and `pdm` used our internal package registry (with netrc for listing credentials)

If PDM 2.0 doesn't read `pip.conf` then I will need to go through and add `tool.pdm.source` to all the `pyproject.toml` files.

Its a small hassle for users with many repos. Too bad pep 621 doesn't have a standard configuration for the index url.

**Comment by sleiner** [comment]
> If PDM 2.0 doesn't read pip.conf then I will need to go through and add `tool.pdm.source` to all the `pyproject.toml` files.
You can configure your PyPI mirror in `pdm.conf` and it will be used by all projects - wouldn't that solve your problem?
