### ISSUE TITLE
Can you please support 3.6?

### ISSUE THREAD

**Issue by SurenNihalani** [frostming/unearth#2]
I am trying to use this and my code base is in 3.6 unfortunately. Could you please support 3.6?

**Describe alternatives you've considered**
Forking and making it 3.6 compatible

**Additional context**

**Comment by frostming** [comment]
I personally don't wanna do that. Because supporting Python 3.6 means we can't use the `from __futures__ import annotations`, which is being used by almost all modules in `unearth`, apart from other API incompatibilities.

Do you find this project useful for you? May I know what are you trying to build?
